FROM php:8.3-fpm

RUN apt-get update && apt-get install -y \
    libpq-dev \
    libzip-dev \
    libpng-dev \
    zip unzip

RUN docker-php-ext-install pdo pdo_pgsql zip gd
RUN apt-get clean

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www

COPY docker_configs/php/start_back.sh /start_back.sh

RUN chmod +x /start_back.sh

CMD ["/start_back.sh"]