FROM node:22-alpine

RUN corepack enable
RUN corepack prepare pnpm@latest --activate

WORKDIR /app

COPY docker_configs/front/start_front.sh /start_front.sh

RUN chmod +x /start_front.sh

CMD ["/start_front.sh"]